# version format
version: 0.1.{build}-{branch}

branches:
  except:
    - gh_pages

skip_tags: true

clone_depth: 1

os: Windows Server 2012 R2

before_build:
  - git submodule update --init
  - mkdir build
  - cd build
  - cmake -G "Visual Studio 14" -DBOOST_ROOT=C:\Libraries\boost_1_59_0 -DBOOST_LIBRARYDIR=C:\Libraries\boost_1_59_0\lib32-msvc-14.0 ..
  - cd ..

build_script:
  - cd build
  - cmake --build . --config Release
  - cd ..

test_script:
  - cd build\test
  - Release\unit_test.exe
